---
local_loopback:
  - name: Loopback1
    desc: Sample Ansible config
    ip_address: 172.20.1.3/24
  - name: Loopback2
    desc: Sample Ansible config
    ip_address: 172.22.1.3/24
  - name: Loopback3
    desc: Sample Ansible config
    ip_address: 172.24.1.3/24
