---
- hosts: ubuntu
  # facts demo
  # ansible ubuntu -m setup
  # ansible ubuntu -m setup -a "filter=*ansible_os_family"
  # ansible ubuntu -m setup -a "filter=*ansible_user_id"
  tasks:
    - name: print OS family to file
      shell: echo "The family is {{ansible_os_family}}" > /home/{{ansible_user_id}}/Desktop/family.txt
    - name: Print Default Machine NIC Name to console
      debug: msg="{{ansible_default_ipv4.interface}}"
    - name: Register ls results variable
      command: "ls"
      register: dirs
    - name: Print dirs variable from last step to console
      debug:
        msg: "{{dirs}}"
