---
- name: Get stats and write to desktop
  hosts: linuxhosts
  tasks:
    - name: get system status and info
      shell: uname -a > /home/knox/Desktop/output.txt
    - name: print my username
      shell: whoami >> /home/knox/Desktop/output.txt