---
- name: Create Loopbacks on device
  hosts: switches
  connection: local
  tasks:
    - name: Create loopback shell
      with_items: "{{local_loopback}}"
      nxos_interface:
        interface: "{{item.name}}"
        mode: layer3
        description: "{{item.desc}}"
        admin_state: up

    - name: Set new loopback configs
      with_items: "{{local_loopback}}"
      nxos_ip_interface:
        state: present
        interface: "{{item.name}}"
        version: v4
        addr: "{{item.ip_address}}"
        mask: "{{item.prefix}}"
