---
local_loopback:
  - name: Loopback1
    desc: Sample Ansible config
    ip_address: 6.6.6.6/32

interfaces:
  - name: GigabitEthernet0/1
    ip_address: 10.99.99.57/30
  - name: GigabitEthernet0/2
    ip_address: 10.99.99.61/30
  - name: GigabitEthernet0/3
    ip_address: 10.99.99.50/30